### ISSUE TITLE
Retrieving product names in mysql instead of php function.

### ISSUE THREAD

**Issue by torvista** [marco-pm/zencart_instantsearch#10]
I note that you are using 
```
$name  = zen_get_products_name($id);
```
instead of getting it in the original sql query.
Do you think that is more efficient?

**Comment by marco-pm** [comment]
I made the change because of [this comment](https://github.com/marco-pm/zencart_instantsearch/issues/5#issue-1223049203)  (see second bullet point). 
I agree that it's less efficient. I'll revert it back, same for `zen_get_category_name`. 
The `NOTIFY_INSTANT_SEARCH_PRIOR_ADD_RESULT` notification can be used to modify the result without changing the code.

**Comment by torvista** [comment]
No need to revert it if there is a valid reason for someone. I doubt that there is any measurable difference.

**Comment by marco-pm** [comment]
Actually it does make a tiny difference, it's an additional db call for every product returned by the query (not just for each of the `MAX_NUMBER_OF_RESULTS` products).
Also I don't like the inconsistent behavior, so I have reverted it back.
