### ISSUE TITLE
firing ossec rule....

### ISSUE THREAD

**Issue by proseLA** [marco-pm/zencart_instantsearch#11]
marco,
first off, great job.  the new release was pretty much plug and play and resolved a css problem i was having on a specific template.  i did not have to even look at the css.  so that was great.

unfortunately, it is now firing a default ossec rule; specifically this one:

https://github.com/ossec/ossec-hids/blob/1ecffb1b884607cb12e619f9ab3c04f530801083/etc/rules/web_appsec_rules.xml#L175-L179

i have turned that rule off for the time being, but considering that is a default rule, perhaps some better timing may be in order?  else maybe i need to slow down on my typing.

best.

**Comment by marco-pm** [comment]
thanks, nice to know that the new version seems to work well!

About your issue, ossec does have a point! (although, I think it should have happened with the previous releases as well, because the js code hasn't changed to that effect).
I have now added a "wait for the end of typing" timeout, configurable via the admin.
Can you please try to install the [latest revision on branch v201](https://github.com/marco-pm/zencart_instantsearch/tree/v201) (see the html readme on how to upgrade the version, because ZC 157 doesn't support upgrade for encapsulated plugins yet) and see if the issue is resolved? The default wait time is 50 ms, if the ossec rule still fires you can try to increase it slightly in the admin and see if that helps.

**Comment by proseLA** [comment]
i had to bring it to 600 ms with my typing to avoid the ossec rule.  i have to give it some more thought to think if that is acceptable or if i need to remove that rule.
